title: Hyperspace
author: Hyperspace Developers

markdown: kramdown
highlighter: rouge

download_config:
  desktop:
    base_url: "https://github.com/hyperspacedev/hyperspace/releases/"
    version: "1.0.4"
    beta_version: "1.1.0-beta4"

collections:
  docs:
    output: true
  releases:
    output: true
